// location
export const RESET_LOCATION = 'RESET_LOCATION';
export const FETCH_LOCATION = 'FETCH_LOCATION';


// locations
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';


// navigation
export const CHANGE_NAVIGATION = 'CHANGE_NAVIGATION';


// user
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const CHANGE_NOTIFICATION_SETTINGS = 'CHANGE_NOTIFICATION_SETTINGS';
